services:
  valkey:
    image: bitnami/valkey:latest
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes: # ephemeral storage
      - valkey_data:/bitnami/valkey/data
volumes:
  valkey_data:
    driver: local
